refactor: Add sources filtering by provider
RHEnVision/provisioning-frontend pull request #194
Opened 2023-02-13 10:17 UTC by adiabramovitch

This is a temporary fix until @amirfefer will finish adding the GCP and Azure UI part.

2023-02-13 10:23 UTC, ezr-ondrej commented on src/Components/DescriptionListAWS/index.js
> +  const { error, data: sources } = useQuery(SOURCES_QUERY_KEY, fetchSourcesList(PROVIDER));
I don't think we necessarily need to filter here :)

2023-02-13 13:07 UTC, ezr-ondrej requested changes

2023-02-13 13:07 UTC, ezr-ondrej commented on src/Components/SourcesSelect/index.js
> +  } = useQuery(SOURCES_QUERY_KEY, fetchSourcesList(PROVIDER), {
we need to pass a function, not it's result here
```suggestion
  } = useQuery(SOURCES_QUERY_KEY, () => fetchSourcesList(PROVIDER), {
```
Or another solution would be to change `fetchSourcesList` to return a function

2023-02-13 20:46 UTC, amirfefer reviewed
Thanks @adiabramovitch 👍 
a rebase with #195 will  give you the provider with no extra constants

In second thought, I've refacored the final descriptation page for general provider, so rebased would be quicker doing the rebase in #195 

Tested with aws and gce sources, works as expected

2023-02-13 20:46 UTC, amirfefer commented on src/Components/DescriptionListAWS/index.js
> +const PROVIDER = 'aws';
with  #195 the `provider` is given by IB and stored in the wizard context

2023-02-14 01:41 UTC, amirfefer approved these changes

2023-02-14 01:43 UTC, merged