Add AWS first step in wizard
RHEnVision/provisioning-frontend pull request #25
Opened 2022-07-10 13:05 UTC by adiabramovitch

2022-07-10 15:36 UTC, amirfefer requested changes
Thanks, @adiabramovitch, looks awwsome! 
Could you please edit the `aria-label` / `aria-describedby` / `fieldId` of the `<Form>`

2022-07-12 09:39 UTC, adiabramovitch commented
@amirfefer  I think the font is bold, how can I change it?

2022-07-12 11:19 UTC, amirfefer commented
>  I think the font is in bold, how can I change it?

which one?

2022-07-12 18:54 UTC, amirfefer reviewed
Thanks @adiabramovitch 👍 Almost ready :)

According to patternfly team, we should use [Select](https://www.patternfly.org/v4/components/select) over `SelectForm`, it supports many options (like a search field for filtering, spinner for loading, normal placeholder :))  but no rush, can be implemented in a follow-up PR

2022-07-12 18:54 UTC, amirfefer commented on src/Components/InstanceTypesSelect/index.js
> +    () => fetchInstanceTypesList(globalState.chosenSource),
- [ ] could you create this function at the top level?  this creates a new function on every re-render

```js
const fetchFunction = () => fetchInstanceTypesList(globalState.chosenSource);
const {
     isLoading,
     error,
     data: instanceTypes,
   } = useQuery(
     TYPES_QUERY_KEY,
     fetchFunction,
   { enabled: !!globalState.chosenSource }

2022-07-13 08:49 UTC, adiabramovitch commented on src/Components/InstanceTypesSelect/index.js
> +    TYPES_QUERY_KEY,
in ther cache key?

2022-07-13 08:50 UTC, adiabramovitch commented on src/Components/Wizard/steps/AccountCustomizations/aws.js
> +        fieldId="simple-form-sources-01"
do we need the 01?

2022-07-13 10:26 UTC, ezr-ondrej approved these changes
Works well locally, I failed to deploy to ephemeral unfortunatelly, but no reason to block on that.

2022-07-13 11:01 UTC, adiabramovitch commented
> Works well locally, I failed to deploy to ephemeral unfortunatelly, but no reason to block on that.

Does that mean you can see the instance types list? :)

2022-07-13 11:24 UTC, amirfefer commented on src/mocks/handlers.js
> +  rest.get(provisioningUrl('instance_types/1'), (req, res, ctx) => {
It uses an express-like path mechanism, like a real server: 

https://mswjs.io/docs/basics/request-matching

2022-07-13 11:26 UTC, amirfefer commented on src/Components/Wizard/steps/AccountCustomizations/aws.js
> +        fieldId="simple-form-sources-01"
it's an id that describes the form field, how `aws-select-source` sounds?

2022-07-13 11:27 UTC, amirfefer commented on src/Components/InstanceTypesSelect/index.js
> +    TYPES_QUERY_KEY,
yes, @ezr-ondrej and @lzap  are not sure if the types is static per account 
so better safe than sorry :)

2022-07-13 12:58 UTC, ezr-ondrej commented
> Does that mean you can see the instance types list? :)

Yes, exactly! :)

2022-07-13 17:06 UTC, amirfefer approved these changes
Thanks @adiabramovitch and @ezr-ondrej  👍

2022-07-13 17:06 UTC, merged