feat(HMS-1245): UI AWS permission check
RHEnVision/provisioning-frontend pull request #292
Opened 2023-08-01 13:27 UTC by avitova

The best way to test this is to insert [a new permission](https://github.com/RHEnVision/provisioning-backend/blob/8bbd98e720e8063ca3bc86b01303af046e636962/internal/clients/http/ec2/iam_client.go#L39) and use your local backend.

2023-08-01 16:51 UTC, akhil-jha commented
Env Build error. Running test again. 
/retest

2023-08-02 08:02 UTC, lzap commented
Do you have a screenshot of the error message? :-)

2023-08-02 13:05 UTC, avitova commented
After a conversation on Slack, we have decided to change this from a step in the stepper to a warning shown only in case of the error. Let me know what you think.
To reproduce this, you can for example use your sources on stage, as well as the image builder, but run the frontend with your local backend where you change the expectedStatement variable. Make sure to produce an error so that the warning is shown. Let me know what you think of this.
![image](https://github.com/RHEnVision/provisioning-frontend/assets/87140865/c75b7148-70eb-4f0a-87ad-5e9d4dbf241c)

2023-08-03 05:27 UTC, akhil-jha commented
/retest

2023-08-07 11:34 UTC, lzap commented
@amirfefer have another PR where he shows a warning message in a different format, please talk to each other and pick one style.

Nitpick: join the permissions with `, ` (comma space)

2023-08-07 12:36 UTC, ezr-ondrej reviewed
Did we test this with Azure? The request for permissions will probably fail, right, do we handle it gracefully? The code doesn't seem to do this explicitly, so at minimum it reads bad, because we run `checkAWSPerms` for all providers.

**Just a thought** (feel free to ignore): did you think about checking the permissions reactively, maybe when we get AWS error. In that way we would save up a request to API and AWS, I do not think it's strictly necessary and this might be a better solution :)

2023-08-07 12:36 UTC, ezr-ondrej commented on src/Components/ProvisioningWizard/steps/ReservationProgress/index.js
> +  const { data } = useQuery([`permissions`, `${chosenRegion}-${chosenSource}`], () => checkAWSPermissions(chosenSource, chosenRegion), {
hmm I wonder... shall we run the check only if the provider is AWS?

2023-08-07 15:26 UTC, lzap commented
> did you think about checking the permissions reactively

Yes, for AWS it means parsing string error and trying to figure out what was wrong. Not too clean.

But good point - this must not break Azure/GCP and it should be implemented in a way that we can easily add the same support into Azure/GCP too.

2023-08-07 15:26 UTC, lzap commented
> because we run `checkAWSPerms` for all providers.

This is bad, needs to be fixed.

2023-08-07 15:50 UTC, amirfefer commented
My concern is it might confuse users. AFAIK,  the error doesn't have to be related to the missing permission, but the error message is hidden, and the warning is highlighted, an advice from @MariSvirik  would help :)

2023-08-08 12:07 UTC, lzap commented on src/Components/ProvisioningWizard/steps/ReservationProgress/index.js
> +            />
So launch will work if the user is missing ListPermission or other related permissions which are only required for the check. Can you reword the warning to something like:

_Warning: Launch may fail, the following permissions are missing: xxxx_

2023-08-08 12:09 UTC, lzap commented
I take my comments on the warning UI back, @amirfefer explained why it is difficult to implement warnings as we would like to. Let’s focus that on later, for now this is a good enough solution.

Summary from our discussion:

* It would be nice to have the check as an extra step before or after Create reservation.
* This step would indicate a warning (perhaps a clickable pop over).
* Multiple warning steps should be supported ideally for the future.
* Significant code changes are required to support that - not subject for this PR.

2023-08-09 12:42 UTC, MariSvirik commented
If the permissions are missing launch will fail, correct?
Right now I see a yellow alert, and a red exclamation mark inside the step and a neutral large icon on the top...so I am not sure if this is still in progress or not.

@lzap what would be that extra step? Do you envision it living inside the wizard?

2023-08-09 13:37 UTC, avitova commented
@MariSvirik No, they will not. Users could set their permissions according to our recommendations, and in that case, we'd be able to find out missing permissions accurately.
But there are ways in which they would not follow [our instructions](https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md), and their setup would work anyways. For example, instead of all the needed permissions, they just insert something like "iam:*" and "ec2:*", which would grant them all currently needed permissions. There are many reasons why it is impossible to detect these rules 100 % accurately.
TLDR; this is just a heads-up for users to check their permissions. I would say this would be helpful when we change the list of expected permissions and need users to update their AWS policies.

2023-08-10 08:38 UTC, lzap commented
Now that I think about it, I think the alternative (and maybe better) solution to this is to take this check few screens before when a source is selected. After source is selected, we can trigger an event of requesting source permission check and display a warning there. What you all think? @ezr-ondrej @amirfefer @avitova @MariSvirik

2023-08-10 15:57 UTC, MariSvirik commented
@lzap that would be great. 
Let's tell the users as soon as possible that there is a problem with permissions.
How long would it take to check?

2023-08-11 14:06 UTC, lzap commented
Tens of milliseconds.

2023-08-21 15:51 UTC, avitova commented
![image](https://github.com/RHEnVision/provisioning-frontend/assets/87140865/c9950828-7f33-49ed-9a1f-4350414f5efe)
So I tried to implement what Maria proposed. Let me know what you think about it now.
We need to now the region and source to find out properly what permissions are missing. This should call the permission validation for every change in one of those fields. I thought it might be 1) safer and 2) better for the future to make the helper function more generic for any provider, so that we only return an empty array for other providers. Let me know your thoughts. :)

2023-08-22 07:27 UTC, avitova commented
/retest

2023-08-22 09:12 UTC, avitova commented
/retest

2023-08-22 10:44 UTC, MariSvirik commented
@avitova How can users fix it? We should tell them.
To make it general we can still include an inline alert in this step with an expandable section that would include missing permissions, but that would be too prominent in my opinion.
Is there any other way to find which permissions are missing if we don't name them in the helper text?

I pinged the doc team to check the text.
<img width="701" alt="Screenshot 2023-08-22 at 12 21 29" src="https://github.com/RHEnVision/provisioning-frontend/assets/51960547/642118ab-8f7b-4fe1-992c-aa752155475c">

2023-08-22 11:45 UTC, ragevou commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +              Warning: Launch may fail, the following permissions are missing: {missingPermissions.join(', ')}
```suggestion
              Warning: Launch can fail, the following permissions are missing: {missingPermissions.join(', ')}
```

2023-08-22 17:38 UTC, amirfefer reviewed
Thanks, @avitova, looks great!
For marking the select warning validation, you can propagate a `validate` prop with a `warning` value to the source select component.

I guess in some cases the list of missing permissions might be long for a helperText, an `ExpandedSection` like @MariSvirik  suggested sounds like a nice solution, also adding some further information on how to add the permissions in the expanded section. You can combine the ExpandedSection  with the helperText component by using the `toggleContent` prop., as you can see in [this](https://codesandbox.io/s/ry7zxv?file=/index.tsx:557-570) live demo

2023-08-22 17:38 UTC, amirfefer commented on src/API/index.js
> +      return [];
`react-query` function needs to be a promise, I double-checked, and returning anything in an `async` block, returns a promise with the status `resolved`, so it should work as expected :)

2023-08-23 11:32 UTC, avitova commented
![image](https://github.com/RHEnVision/provisioning-frontend/assets/87140865/0a9ad948-bdcb-4455-903e-ca09628c6001)
Thank you both @MariSvirik and @amirfefer, for your comments. I have tried to do the permission check more general, even though it is implemented only for AWS for now.
I thought we could also have a ToolTip for missing permissions, but the list could get really long, so maybe it is not the best idea. The expandable section looks like a good idea. I am a bit worried about the scrollbar though. Let me know what you think.

2023-08-24 12:48 UTC, MariSvirik commented
@avitova 
I talked to other designers and we decided on an [inline expandable alert](https://www.patternfly.org/components/alert/html-demos/inline-alert-in-horizontal-form/).
Patternfly doesn't use an expandable plain alert component - as displayed on your screenshot. When there is a problem in the field, use [this](https://www.patternfly.org/components/alert/html-demos/inline-alert-in-horizontal-form/) or [this](https://www.patternfly.org/components/forms/form-control#select) for select. (An inline alert may or may not be used there)

my proposal:
the message is general. When expanded, users can see the list of permissions and where to check it. Would it be possible to add a link where they can check those permissions?
<img width="657" alt="Screenshot 2023-08-24 at 14 37 57" src="https://github.com/RHEnVision/provisioning-frontend/assets/51960547/26142fa7-6326-4919-ae73-f26144439968">
<img width="481" alt="Screenshot 2023-08-24 at 14 40 45" src="https://github.com/RHEnVision/provisioning-frontend/assets/51960547/045e2750-1a7d-4652-8baa-e8816ca2f521">

2023-08-24 14:52 UTC, avitova commented
![image](https://github.com/RHEnVision/provisioning-frontend/assets/87140865/1acd4782-f5f4-4711-b40b-42d9ed07661e)
Nice! We are getting closer and closer. Thank you for your patience. :heart:

2023-08-25 12:39 UTC, avitova commented
![chrome-capture-2023-7-25 (5)](https://github.com/RHEnVision/provisioning-frontend/assets/87140865/430ec3fe-e9e4-4d4a-ba8c-85470a5ca7ae)
After conversations with Maria, I have incorporated her input into the changes made.

2023-08-28 13:18 UTC, lzap commented
Idea: Implement some limit, if list of missing permission is longer than let’s say 5 you can generate: perm1, perm2, perm3 and 2 more.

2023-09-06 09:31 UTC, amirfefer requested changes
Thanks @avitova! It looks great! 
I left a few inline comments, mostly nitpicks, and also please verify that the form validation is not broken due to the `default` addition to the region field.

2023-09-08 10:46 UTC, ezr-ondrej commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
Could we ... in theory... have the permission list extracted to a file in the backend and load it in code here on the build time - or figure out how to load it to documentation on build time?

We can also play with it as next step tho. I'd either link Sources directly with "Make sure you're following the steps while creating source", or link the official sources documentation with similar message :shrug:

2023-09-08 10:48 UTC, ezr-ondrej commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
Linking to developer docs is not terrible, just not profesional, but given we are explaining the process quite deeply there I'm mostly worried customers might get confused by all the info there :)

2023-09-11 08:26 UTC, avitova commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
I am not sure how we'd want to show the long list here. The link seems like the only sensible option, but I am open if you see a way to show it. We could have one more expandable section with the required permissions if that makes sense.

2023-09-12 08:51 UTC, avitova commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
Do you suggest we hardcode the list of permissions to the official docs for now? Yeah, we could do that, and add it to the [https://github.com/RHEnVision/provisioning-backend/blob/main/CONTRIBUTING.md#basic-guidelines-for-code-contributions](list of places to change).
At the moment, we need to load the permission list to:
- Go file
- Javascript file
- yaml
- markdown

And we can try to eliminate some of these. :thinking:

2023-09-12 09:28 UTC, ezr-ondrej commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
I'm suggesting to split the IAM policy: https://github.com/RHEnVision/provisioning-backend/pull/682 and the include it on build time here

2023-09-12 09:43 UTC, ezr-ondrej commented on src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
> +                <a href="https://github.com/RHEnVision/provisioning-backend/blob/main/docs/configure-amazon-role.md#service-account-policy">
Contributing guide is perfect first step for sure :)

2023-10-09 13:55 UTC, closed without merging